### ISSUE TITLE
7 error compile project

### ISSUE THREAD

**Issue by Angelk90** [cesardeazevedo/react-native-nested-scroll-view#1]
I had to use react-native-collapsing-toolbar so I installed both,
React-native-collapsing-toolbar that react-native-nested-scroll-view.

I did: react-native link
Then I did: react-native run-android, all right until I get these 7 errors at the time of compilation:
![error](https://user-images.githubusercontent.com/20476002/29413440-ac18df9c-835c-11e7-887f-8bc41606ac39.png)

"dependencies": {
		"native-base": "^2.3.1",
		"react": "16.0.0-alpha.12",
		"react-native": "^0.46.4",
		"react-native-collapsing-toolbar": "^1.0.0-beta.4",
		"react-native-image-slider": "^1.1.5",
		"react-native-linear-gradient": "^2.2.0",
		"react-native-nested-scroll-view": "^3.0.0",
		"react-native-vector-icons": "^4.3.0",
		"react-native-video": "^1.2.0",
		"react-native-video-player": "^0.8.1",
		"react-navigation": "^1.0.0-beta.11"
	},

@cesardeazevedo: How can I fix it?

**Comment by cesardeazevedo** [comment]
Hi, react-native-nested-scroll-view@3.0.0 are shipped with react-native 0.47, so you should use 2.0.0 instead to work with react-native 0.46, for react-native-collapsing-toolbar you should use the version 1.0.0-beta.4.

let me know if you got it.

**Comment by Angelk90** [comment]
@cesardeazevedo: I did as you told me about the following problem:
![error](https://user-images.githubusercontent.com/20476002/29426595-6346f54e-8387-11e7-8d5b-b2c1792a83c7.png)

So this time the error is in the other module.

P.Š.
Do you know a way to have the error log in a text file?

**Comment by cesardeazevedo** [comment]
Hi, i am not sure on what's going on, but can you compare your build.gradle with this [build.gradle](https://github.com/cesardeazevedo/react-native-collapsing-toolbar/blob/master/example/android/app/build.gradle)? make sure that you're using the same `targetSdkVersion` version and `com.android.support:design:25.3.1`

**Comment by Angelk90** [comment]
In the end after so many problems with react native 0.47.1, I managed to run it.
So I let go of the old version, but I'll send you the latest build.gradle file, which I have of that version.
[build.gradle.txt](https://github.com/cesardeazevedo/react-native-nested-scroll-view/files/1236713/build.gradle.txt)
