### ISSUE TITLE
Error when run on iOS

### ISSUE THREAD

**Issue by nghialt** [cesardeazevedo/react-native-nested-scroll-view#11]
Hi @cesardeazevedo, I'm facing an issue when run on iOS: 

> Tried to register two views with the same name RCTScrollContentView
>
> register
> ReactNativeFiber-dev.js:3028:29
> unknown
> NestedScrollView.js:874:48
> ...

I tried to comment the code block from line 860 to 874 in file NestedScrollView.js, it can load properly.

Any idea to fix this issue?

Best regards.

**Comment by cesardeazevedo** [comment]
Since this project is Android only, i highly recommend you split logic between `.android.js` and `.ios.js`, but that's indeed, it should fallback to the default ScrollView implementation on ios, so i'm going to fix it.

**Comment by Jacse** [comment]
Looks like I'm still getting this error on `5.0.2`.

**Comment by Jacse** [comment]
Error is still present on `6.0.0`

**Comment by cesardeazevedo** [comment]
That's indeed very weird, i will investigate.

**Comment by cesardeazevedo** [comment]
Sorry for the delayed guys, i just pushed a fix at `6.0.1`.

Tell me if you had any more issues with it.
Thanks
