### ISSUE TITLE
ScrollView/InternalScrollViewType error

### ISSUE THREAD

**Issue by davidchuyaya** [cesardeazevedo/react-native-nested-scroll-view#25]
I'm building on RN 0.55.2 for Android, bundling the app before running with this code (from Stackoverflow):

`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

I'm hitting this error:

``Loading dependency graph...
Unable to resolve module `react-native/Libraries/Components/ScrollView/InternalScrollViewType` from `.../node_modules/react-native-nested-scroll-view/lib/NestedScrollView.js`: Module `react-native/Libraries/Components/ScrollView/InternalScrollViewType` does not exist in the Haste module map``

**Comment by cesardeazevedo** [comment]
Hi, the last version only works with react-native 0.56.0, upgrade react-native or use an old version of this package.

**Comment by davidchuyaya** [comment]
Understood.
