### ISSUE TITLE
InternalScrollViewType missing

### ISSUE THREAD

**Issue by tponte** [cesardeazevedo/react-native-nested-scroll-view#37]
Hi,

I have a problem using the library after upgrading react native to the new 0.60 version.

The library uses react native's InternalScrollViewType in the NestedScrollView.js
file, but it's missing in versions =>0.60.

I've tested exporting the ScrollView instead of TypedScrollView and it seems to work well.

**Comment by prateekchachra** [comment]
+1

**Comment by mahyali** [comment]
+1

**Comment by ikedm** [comment]
+1

**Comment by branikclimbs** [comment]
+1

**Comment by MasoudShah** [comment]
+1

**Comment by cesardeazevedo** [comment]
Working on this

**Comment by cesardeazevedo** [comment]
Fixed at `9.0.0`

**Comment by sdjhoanborges** [comment]
+1 and using "react-native-nested-scroll-view": "^9.0.0",
