### ISSUE TITLE
ReactNestedScrollViewManager.java:145: error: method does not override or implement a method from a supertype (flashScrollIndicators)

### ISSUE THREAD

**Issue by chiasheang** [cesardeazevedo/react-native-nested-scroll-view#9]
"react": "16.0.0-alpha.12",
"react-native": "0.48.3",
"react-native-nested-scroll-view": "^5.0.1",

**Comment by cesardeazevedo** [comment]
version 5.0.1 works with react-native 49

**Comment by cesardeazevedo** [comment]
I'm going to close this, hope you got it.
